name: ‚öôÔ∏è Serverless AWS Deploy-Test

on:
  push:
    branches: [ "develop" ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: ‚öôÔ∏è Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: ‚öôÔ∏è Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --no-cache-dir
        python3.9 -V
    - name: ‚öôÔ∏è Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: ‚öôÔ∏è Install Node.js dependencies
      run: |
        npm install -g serverless
        npm install
    - name: üì¶ Serverless AWS Deploy
      run: |
        serverless config credentials -p aws -k ${{ secrets.AWS_ACCESS_KEY_ID }} -s ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        serverless deploy --region us-east-1 --stage dev
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
